// Shared subject matching utilities used by recommendations, exams and notifications.

const normalize = (str) => String(str).toLowerCase().trim();

const subjectAliases = {
  // CS / IT / MCA
  'operating systems': ['os'],
  'object oriented programming': ['java', 'oops'],
  'object oriented programming in java': ['java', 'oops'],
  'data structures': ['dsa'],
  'database management systems': ['dbms', 'sql'],
  'computer organization': ['coa', 'computer architecture'],
  'computer networks': ['networks', 'cn'],
  'web technologies': ['web dev', 'web development'],
  'artificial intelligence': ['ai'],
  'machine learning': ['ml'],
  'cyber security': ['security', 'cyber'],
  'cloud computing': ['cloud'],
  'big data analytics': ['big data', 'data analytics'],
  'data mining': ['data mining'],
  'mobile application development': ['mobile', 'android', 'ios'],
  'internet of things': ['iot'],
  'blockchain technology': ['blockchain'],
  'natural language processing': ['nlp'],
  'computer graphics': ['graphics'],
  'compiler design': ['compilers'],
  'theory of computation': ['toc', 'automata'],
  'digital electronics': ['de', 'digital logic'],
  'discrete mathematics': ['maths', 'mathematics'],
  'probability & statistics': ['maths', 'mathematics', 'statistics', 'probability'],
  'mathematics i': ['maths', 'mathematics'],
  'mathematics ii': ['maths', 'mathematics'],
  'linear algebra': ['maths', 'mathematics'],
  'numerical methods': ['maths', 'mathematics'],
  'optimization techniques': ['maths', 'mathematics'],
  'design & analysis of algorithms': ['dsa', 'algorithms'],
  'python programming': ['python'],
  'problem solving & programming in c': ['c', 'programming'],
  'programming in c': ['c', 'programming'],

  // Sciences
  'mathematical physics': ['physics', 'maths', 'mathematics'],
  'classical mechanics': ['physics'],
  'quantum mechanics': ['physics'],
  'quantum mechanics i': ['physics'],
  'quantum mechanics ii': ['physics'],
  'electrodynamics': ['physics'],
  'statistical mechanics': ['physics'],
  'solid state physics': ['physics'],
  'nuclear & particle physics': ['physics'],
  'laser physics': ['physics'],
  'optics': ['physics'],
  'mechanics': ['physics'],
  'thermodynamics': ['physics', 'chemistry'],
  'computational physics': ['physics'],
  'electronics': ['electronics', 'physics'],

  'inorganic chemistry': ['chemistry'],
  'inorganic chemistry i': ['chemistry'],
  'inorganic chemistry ii': ['chemistry'],
  'organic chemistry': ['chemistry'],
  'organic chemistry i': ['chemistry'],
  'organic chemistry ii': ['chemistry'],
  'physical chemistry': ['chemistry'],
  'physical chemistry i': ['chemistry'],
  'physical chemistry ii': ['chemistry'],
  'analytical chemistry': ['chemistry'],
  'spectroscopy': ['chemistry'],
  'organic synthesis': ['chemistry'],
  'polymer chemistry': ['chemistry'],
  'coordination chemistry': ['chemistry'],
  'electrochemistry': ['chemistry'],
  'surface chemistry': ['chemistry'],
  'green chemistry': ['chemistry'],
  'medicinal chemistry': ['chemistry'],
  'nanochemistry': ['chemistry'],
  'catalysis': ['chemistry'],
  'photochemistry': ['chemistry'],
  'natural products': ['chemistry'],
  'computational chemistry': ['chemistry'],
  'environmental chemistry': ['chemistry'],
  'industrial chemistry': ['chemistry'],
  'engineering chemistry': ['chemistry'],

  'real analysis': ['maths', 'mathematics'],
  'complex analysis': ['maths', 'mathematics'],
  'abstract algebra': ['maths', 'mathematics'],
  'topology': ['maths', 'mathematics'],
  'number theory': ['maths', 'mathematics'],
  'differential equations': ['maths', 'mathematics'],
  'probability theory': ['maths', 'mathematics', 'probability'],
  'functional analysis': ['maths', 'mathematics'],
  'stochastic processes': ['maths', 'mathematics'],
  'graph theory': ['maths', 'mathematics'],
  'financial mathematics': ['maths', 'mathematics', 'finance'],

  // MBA / Management
  'organizational behavior': ['management', 'hr'],
  'marketing management': ['marketing', 'management'],
  'financial accounting': ['finance', 'accounting', 'management'],
  'business statistics': ['statistics', 'management'],
  'human resource management': ['hr', 'management'],
  'financial management': ['finance', 'management'],
  'operations management': ['operations', 'management'],
  'business research methods': ['research', 'management'],
  'business law': ['law', 'management'],
  'strategic management': ['strategy', 'management'],
  'consumer behavior': ['marketing', 'management'],
  'entrepreneurship': ['business', 'management'],
  'digital marketing': ['marketing', 'management'],
  'project management': ['management'],
  'international business': ['management'],
  'leadership & ethics': ['leadership', 'management'],
  'managerial economics': ['economics', 'management'],

  // Architecture
  'architectural design i': ['architecture'],
  'architectural design ii': ['architecture'],
  'architectural design iii': ['architecture'],
  'architectural design iv': ['architecture'],
  'architectural design v': ['architecture'],
  'architectural design vi': ['architecture'],
  'architectural design vii': ['architecture'],
  'architectural design viii': ['architecture'],
  'architectural design ix': ['architecture'],
  'building materials': ['architecture'],
  'structural mechanics': ['architecture'],
  'history of architecture': ['architecture'],
  'theory of design': ['architecture'],
  'construction technology': ['architecture'],
  'landscape architecture': ['architecture'],
  'urban design': ['architecture'],
  'working drawing': ['architecture'],
  'specifications & estimation': ['architecture'],
  'professional practice': ['architecture'],
  'sustainable architecture': ['architecture'],
  'town planning': ['architecture'],
  'conservation': ['architecture'],
  'advanced construction': ['architecture'],
  'research methodology': ['research'],

  // Electrical & Electronics
  'electrical machines': ['electrical machines i', 'electrical machines ii', 'em', 'ee'],
  'power systems': ['power systems i', 'power systems ii', 'ps'],
  'control systems': ['control systems', 'cs'],
  'power electronics': ['power electronics', 'pe'],
  'signals & systems': ['signals and systems', 's&s'],
  'digital electronics': ['digital electronics', 'de'],
  'analog circuits': ['analog circuits', 'analog electronics'],
  'microprocessors': ['microprocessor', 'mp'],
  'vlsi design': ['vlsi', 'vlsi design'],
  'communication systems': ['communication systems', 'comm sys'],
  'digital signal processing': ['dsp', 'digital signal processing'],
  'embedded systems': ['embedded systems', 'embedded'],
  'electromagnetic theory': ['electromagnetic theory', 'emt'],
  'electromagnetic fields': ['electromagnetic fields', 'emf'],
  'electrical drives': ['electrical drives', 'drives'],
  'renewable energy': ['renewable energy systems', 'renewable energy'],
  'smart grid': ['smart grid'],
  'high voltage engineering': ['high voltage engineering', 'hv'],
  'switchgear & protection': ['switchgear', 'protection'],
  'power system analysis': ['power system analysis'],
  'instrumentation': ['instrumentation'],
  'network analysis': ['network analysis'],
  'optical communication': ['optical communication'],
  'wireless communication': ['wireless communication'],
  'antenna & wave propagation': ['antenna', 'wave propagation'],
  'microwave engineering': ['microwave engineering'],
  'mobile communication': ['mobile communication'],
  'radar systems': ['radar systems'],
  'image processing': ['image processing'],
  'robotics': ['robotics'],
  'internet of things': ['iot'],
  'nanotechnology': ['nanotechnology'],
  'satellite communication': ['satellite communication'],

  // Mechanical
  'fluid mechanics': ['fluid mechanics', 'fm'],
  'thermodynamics': ['thermodynamics', 'thermal'],
  'heat transfer': ['heat transfer', 'ht'],
  'manufacturing processes': ['manufacturing processes', 'manufacturing'],
  'kinematics of machines': ['kinematics of machines', 'kom'],
  'dynamics of machines': ['dynamics of machines', 'dom'],
  'machine design': ['machine design', 'machine design i', 'machine design ii'],
  'industrial engineering': ['industrial engineering'],
  'cad/cam': ['cad', 'cam', 'cad/cam'],
  'finite element analysis': ['finite element analysis', 'fea'],
  'mechanical vibrations': ['mechanical vibrations'],
  'turbo machinery': ['turbo machinery'],
  'automobile engineering': ['automobile engineering'],
  'refrigeration & air conditioning': ['refrigeration', 'rac'],
  'operations research': ['operations research', 'or'],
  'quality control': ['quality control', 'qc'],
  'supply chain management': ['supply chain management', 'scm'],
  'project management': ['project management'],
  'ergonomics': ['ergonomics'],
  'lean manufacturing': ['lean manufacturing'],
  'six sigma': ['six sigma'],
  'tool design': ['tool design'],
  'metrology': ['metrology'],
  'strength of materials': ['strength of materials', 'som'],
  'engineering mechanics': ['engineering mechanics'],
  'composite materials': ['composite materials'],

  // Civil
  'structural analysis': ['structural analysis', 'structural analysis i', 'structural analysis ii'],
  'concrete technology': ['concrete technology'],
  'geotechnical engineering': ['geotechnical engineering'],
  'transportation engineering': ['transportation engineering'],
  'hydrology': ['hydrology'],
  'design of concrete structures': ['design of concrete structures', 'drc'],
  'design of steel structures': ['design of steel structures'],
  'irrigation engineering': ['irrigation engineering'],
  'environmental engineering': ['environmental engineering'],
  'construction management': ['construction management'],
  'earthquake engineering': ['earthquake engineering'],
  'pavement design': ['pavement design'],
  'remote sensing': ['remote sensing'],
  'bridge engineering': ['bridge engineering'],
  'foundation engineering': ['foundation engineering'],
  'town planning': ['town planning'],
  'sustainable construction': ['sustainable construction'],
  'surveying': ['surveying'],
  'gis': ['gis'],

  // Chemical
  'chemical process calculations': ['chemical process calculations'],
  'mechanical operations': ['mechanical operations'],
  'mass transfer': ['mass transfer'],
  'chemical reaction engineering': ['chemical reaction engineering', 'cre'],
  'process instrumentation': ['process instrumentation'],
  'transport phenomena': ['transport phenomena'],
  'process control': ['process control'],
  'petroleum refining': ['petroleum refining'],
  'polymer technology': ['polymer technology'],
  'environmental engineering': ['environmental engineering'],
  'plant design': ['plant design'],
  'biochemical engineering': ['biochemical engineering'],
  'fertilizer technology': ['fertilizer technology'],
  'catalysis': ['catalysis'],
  'process optimization': ['process optimization'],
  'safety engineering': ['safety engineering'],
  'process modeling': ['process modeling'],
  'membrane technology': ['membrane technology'],
  'energy engineering': ['energy engineering'],
  'organic chemistry': ['organic chemistry', 'organic chemistry i', 'organic chemistry ii'],
  'inorganic chemistry': ['inorganic chemistry', 'inorganic chemistry i', 'inorganic chemistry ii'],
  'physical chemistry': ['physical chemistry', 'physical chemistry i', 'physical chemistry ii'],

  // Sciences - Mathematics
  'real analysis': ['real analysis'],
  'complex analysis': ['complex analysis'],
  'abstract algebra': ['abstract algebra'],
  'topology': ['topology'],
  'number theory': ['number theory'],
  'differential equations': ['differential equations'],
  'probability theory': ['probability theory'],
  'functional analysis': ['functional analysis'],
  'stochastic processes': ['stochastic processes'],
  'graph theory': ['graph theory'],
  'financial mathematics': ['financial mathematics'],
  'numerical methods': ['numerical methods', 'numerical analysis'],
  'linear algebra': ['linear algebra'],
  'optimization techniques': ['optimization techniques'],
  'discrete mathematics': ['discrete mathematics'],

  // Sciences - Physics
  'mathematical physics': ['mathematical physics'],
  'classical mechanics': ['classical mechanics'],
  'quantum mechanics': ['quantum mechanics', 'quantum mechanics i', 'quantum mechanics ii'],
  'electrodynamics': ['electrodynamics'],
  'statistical mechanics': ['statistical mechanics'],
  'solid state physics': ['solid state physics'],
  'nuclear physics': ['nuclear physics', 'nuclear & particle physics'],
  'atomic & molecular physics': ['atomic & molecular physics'],
  'laser physics': ['laser physics'],
  'optics': ['optics'],
  'electronics': ['electronics'],
  'computational physics': ['computational physics'],
  'condensed matter physics': ['condensed matter physics'],
  'particle physics': ['particle physics'],
  'plasma physics': ['plasma physics'],
  'astrophysics': ['astrophysics'],
  'nanophysics': ['nanophysics'],
  'quantum field theory': ['quantum field theory'],
  'general relativity': ['general relativity'],
  'semiconductor physics': ['semiconductor physics'],
  'biophysics': ['biophysics'],
  'materials science': ['materials science'],
  'optoelectronics': ['optoelectronics'],
  'superconductivity': ['superconductivity'],
  'surface physics': ['surface physics'],

  // Sciences - Chemistry
  'analytical chemistry': ['analytical chemistry'],
  'spectroscopy': ['spectroscopy'],
  'organic synthesis': ['organic synthesis'],
  'polymer chemistry': ['polymer chemistry'],
  'coordination chemistry': ['coordination chemistry'],
  'electrochemistry': ['electrochemistry'],
  'surface chemistry': ['surface chemistry'],
  'green chemistry': ['green chemistry'],
  'medicinal chemistry': ['medicinal chemistry'],
  'nanochemistry': ['nanochemistry'],
  'organometallic chemistry': ['organometallic chemistry'],
  'supramolecular chemistry': ['supramolecular chemistry'],
  'heterocyclic chemistry': ['heterocyclic chemistry'],
  'corrosion science': ['corrosion science'],
  'photochemistry': ['photochemistry'],
  'natural products': ['natural products'],
  'computational chemistry': ['computational chemistry'],
  'environmental chemistry': ['environmental chemistry'],
  'industrial chemistry': ['industrial chemistry'],

  // MBA / Management
  'organizational behavior': ['organizational behavior', 'ob'],
  'marketing management': ['marketing management'],
  'financial accounting': ['financial accounting'],
  'business statistics': ['business statistics'],
  'human resource management': ['human resource management', 'hrm', 'hr'],
  'financial management': ['financial management'],
  'operations management': ['operations management'],
  'business research methods': ['business research methods'],
  'business law': ['business law'],
  'strategic management': ['strategic management'],
  'consumer behavior': ['consumer behavior'],
  'entrepreneurship': ['entrepreneurship'],
  'digital marketing': ['digital marketing'],
  'project management': ['project management'],
  'international business': ['international business'],
  'leadership & ethics': ['leadership & ethics', 'leadership', 'ethics'],
  'managerial economics': ['managerial economics'],
  'brand management': ['brand management'],
  'sales management': ['sales management'],
  'public relations': ['public relations'],
  'corporate governance': ['corporate governance'],
  'talent management': ['talent management'],
  'e-commerce': ['e-commerce'],
  'business analytics': ['business analytics'],

  // Architecture
  'architectural design': ['architectural design', 'architectural design i', 'architectural design ii', 'architectural design iii', 'architectural design iv', 'architectural design v', 'architectural design vi', 'architectural design vii', 'architectural design viii', 'architectural design ix'],
  'building materials': ['building materials'],
  'structural mechanics': ['structural mechanics'],
  'history of architecture': ['history of architecture'],
  'theory of design': ['theory of design'],
  'construction technology': ['construction technology'],
  'landscape architecture': ['landscape architecture'],
  'urban design': ['urban design'],
  'working drawing': ['working drawing'],
  'specifications & estimation': ['specifications & estimation'],
  'town planning': ['town planning'],
  'professional practice': ['professional practice'],
  'sustainable architecture': ['sustainable architecture'],
  'conservation': ['conservation'],
  'advanced construction': ['advanced construction'],
  'housing': ['housing'],
  'interior design': ['interior design'],
  'building economics': ['building economics'],
  'thesis': ['thesis i', 'thesis ii', 'thesis prep'],

  // Generic mappings
  physics: ['physics'],
  chemistry: ['chemistry'],
  mathematics: ['maths', 'mathematics'],
  maths: ['maths', 'mathematics'],
};

const romanNumeralSuffix = /\s+(i|ii|iii|iv|v|vi|vii|viii|ix|x)$/;

const baseSubjectName = (norm) => norm.replace(romanNumeralSuffix, '');

const expandSubject = (subject) => {
  const norm = normalize(subject);
  const aliases = subjectAliases[norm] || [];
  const base = baseSubjectName(norm);
  const baseAliases = base !== norm ? (subjectAliases[base] || []) : [];
  return [norm, ...aliases, base, ...baseAliases];
};

const resourceTerms = (resource) => {
  const terms = new Set([normalize(resource.category)]);
  (resource.tags || []).forEach((tag) => terms.add(normalize(tag)));
  return [...terms];
};

const matchesSubjects = (text, subjects) => {
  const expanded = expandSubject(text);
  return subjects.some((subject) => {
    const subjectTerms = expandSubject(subject);
    return expanded.some((term) => subjectTerms.includes(term));
  });
};

const resourceMatchesSubjects = (resource, subjects) => {
  const terms = resourceTerms(resource);
  return subjects.some((subject) => {
    const subjectTerms = expandSubject(subject);
    return terms.some((term) => subjectTerms.includes(term));
  });
};

const textMatchesSubjects = (text, subjects) => {
  const normText = normalize(text);
  return subjects.some((subject) => {
    const subjectTerms = expandSubject(subject);
    return subjectTerms.some((term) => normText.includes(term) || term.includes(normText));
  });
};

export {
  normalize,
  subjectAliases,
  expandSubject,
  resourceMatchesSubjects,
  textMatchesSubjects,
  matchesSubjects,
};
